language: node_js
node_js:
  - '0.10'
  - '0.12'
  - stable
cache:
  directories:
    - node_modules
    - test/tmp/deps/node_modules
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install sass
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install
script:
  - gulp test
after_script:
  - gulp build
